# Generated by Django 5.2.7 on 2025-10-08 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, help_text='A short, one-paragraph summary or verdict for the review.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
