# Generated by Django 5.2.7 on 2025-10-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('social_links', models.JSONField(default=dict)),
            ],
        ),
    ]
