# Generated by Django 5.2.7 on 2025-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('display_position', models.CharField(choices=[('HOMEPAGE_TOP', 'Homepage Top Banner'), ('SIDEBAR', 'Sidebar Ad'), ('ARTICLE_INLINE', 'In-Article Ad')], max_length=50)),
            ],
        ),
    ]
